@url = http://localhost:3000/api/workplaces

GET {{url}}/all

###POST
POST {{url}}/new
Content-Type: application/json

{ "name": "Alcalá", "active":true }

###
DELETE {{url}}/delete
Content-Type: application/json

{ "name": "NoDestruido", "active": true, "id": 2}


###
PUT {{url}}/update
Content-Type: application/json

{ "name": "Mollet", "active": true, "code": 3}

###
PUT {{url}}/update
Content-Type: application/json

{ "name": "Mollet desc", "active": false, "code": 3}